parameters:
    caxy_elasticsearch.resetter.class: Caxy\Bundle\ElasticsearchBundle\Resetter
#    caxy_elasticsearch.monolog.processor.class: Monolog\Processor\IntrospectionProcessor

services:
    caxy_elasticsearch.resetter:
        class: %caxy_elasticsearch.resetter.class%
        arguments: [ @caxy_elasticsearch.client, %caxy_elasticsearch.setup%, %caxy_elasticsearch.index.params%, %caxy_elasticsearch.mapping.params% ]

#    caxy_elasticsearch.monolog.processor:
#        class: %caxy_elasticsearch.monolog.processor.class%
#        tags:
#            - { name: monolog.handler, channel: elasticsearch }
