parameters:
#    ushios_elastic_search.example.class: Ushios\Bundle\ElasticSearchBundle\Example

services:
#    ushios_elastic_search.example:
#        class: %ushios_elastic_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
